CREATE TABLE memory_insight (
    id BIGINT NOT NULL AUTO_INCREMENT,
    insight_key VARCHAR(36) NOT NULL,
    memory_id BIGINT NOT NULL,
    source_version BIGINT NOT NULL,
    quote_field VARCHAR(20) NOT NULL,
    quote VARCHAR(800) NOT NULL,
    statement VARCHAR(500) NOT NULL,
    direction VARCHAR(20) NOT NULL,
    aspect VARCHAR(20) NOT NULL,
    factor VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    origin VARCHAR(20) NOT NULL,
    ai_call_key VARCHAR(36) NULL,
    suggested_quote_field VARCHAR(20) NULL,
    suggested_quote VARCHAR(800) NULL,
    suggested_statement VARCHAR(500) NULL,
    suggested_direction VARCHAR(20) NULL,
    suggested_aspect VARCHAR(20) NULL,
    suggested_factor VARCHAR(100) NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_mi_insight_key UNIQUE (insight_key),
    CONSTRAINT fk_mi_memory FOREIGN KEY (memory_id) REFERENCES anime_memory(id) ON DELETE CASCADE,
    INDEX idx_mi_memory (memory_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
